version: '3.8'
services:
  web:
    build:
      ports:
        - "5000:5000"
  db:
    image: "postgres"
    container_name: "my_postgres"
    environment:
      - POSTGRES_USER=oalabede
      - POSTGRES_PASSWORD=summertime82
      - POSTGRES_DB=mydb
      - "54320:5432"
    volumes:
    - ./postgres-data:/var/lib/postgresql/data